id: d2c62705271842eea81befcf47170aac
initial_creation_type: ocr
source_metadata:
  volumes:
    a036a677e5114f908f057ba0b1bf055f:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: རྡོ་རྗེ་ཕག་མོའི་སྒྲུབ་ཐབས།
      total_pages: 1902
      volume_number: 26
